image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apk add --update git nodejs npm
    - mkdir themes
    - cd themes
    - git clone https://github.com/Jack-alope/sourgough-starter.git
    - cd ..
    - node resources/_gen/assets/js/scholar-stats.js
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main
