image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apk add --update git nodejs npm make
    - npm install --save request request-promise cheerio puppeteer
    - mkdir themes
    - git clone https://github.com/Jack-alope/sourgough-starter.git themes/sourgough-starter
    - node static/js/scholar-stats.js
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main
