image: python:latest
    
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - echo "Hi"

run:
  script:
      - sed -i '$$d' README.md
      - date >> README.md
      - git add -A
      - git commit -m "Locked PDF"
      - git push origin post --force || true
