image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apk add --update git nodejs npm make
    - make
    - hugo
  artifacts:
    paths:
      - public
  only:
    - main
