name: Reload ciation data

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Readme
      run: |
        npm install --save request request-promise cheerio puppeteer
        node static/js/scholar-stats.js
        rm -f lastUpdated.md
        date >> lastUpdated.md
    - name: Commit files
      run: |
        git config --local user.name "Github Action"
        git add .
        git commit -m "Updated Citation Data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
